version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      timezone: Europe/Madrid
    open-pull-requests-limit: 10
    labels:
      - "dependencies"